trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

stages:
 - template: azure/nightly-stages.yml@templates
   
resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.2
      endpoint: qdot
