[package]
name = "buttplug"
version = "0.1.0"
authors = ["Kyle Machulis <kyle@machul.is>"]
description = "Cross Platform Sex Toy Control Server"
license = "BSD-3-Clause"
homepage = "http://github.com/metafetish/buttplug"
repository = "https://github.com/metafetish/buttplug.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware"]

[dependencies]
libtrancevibe = "^0.1.0"
lovesense = "^0.1.0"
clap = {version = "2", features = ["yaml"]}
ws = "^0.5.3"
serde_json = "^0.8.2"
serde = "^0.8.9"
serde_macros = "^0.8.9"
aster = "^0.29"
# clippy = "^0.0.91"
bytes = "^0.3.0"
mio = "^0.6.0"
env_logger = "*"
log = "*"
