[package]
name = "buttplug"
version = "0.0.2"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Buttplug Intimate Hardware Control Library"
license = "BSD-3-Clause"
homepage = "http://buttplug.io"
repository = "https://github.com/buttplugio/buttplug-rs.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]

[dependencies]
serde_json = "*"
serde_derive = "*"
serde = "*"
bytes = "*"
env_logger = "*"
log = "*"

[lib]
name = "buttplug"
path = "src/lib.rs"
test = true
doctest = true
doc = true