[package]
name = "buttplug"
version = "0.0.2"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Buttplug Intimate Hardware Control Library"
license = "BSD-3-Clause"
homepage = "http://buttplug.io"
repository = "https://github.com/buttplugio/buttplug-rs.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"

[dependencies]
serde_json = "1.0.40"
serde_derive = "1.0.101"
serde = "1.0.101"
bytes = "0.4.12"
env_logger = "0.7.0"
log = "0.4.8"
quote = "*"
syn = "*"
buttplug_derive = { path = "./buttplug_derive" }

[lib]
name = "buttplug"
path = "src/lib.rs"
test = true
doctest = true
doc = true
proc-macro = true