[package]
name = "buttplug_ws_connector"
version = "0.1.0"
authors = ["Kyle Machulis <kyle@nonpolynomial.com>"]
edition = "2018"

[dependencies]
buttplug = { path = "../buttplug" }
futures-preview = {version="0.3.0-alpha.19", features = ["async-await"]}
ws = "0.9.1"
async-std = {version="0.99.11", features=["unstable"]}
async-trait = "0.1.17"
log = "0.4.8"

[dev-dependencies]
env_logger = "0.7.1"
