[package]
name = "buttplug"
version = "6.0.0"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Buttplug Intimate Hardware Control Library"
license = "BSD-3-Clause"
homepage = "http://buttplug.io"
repository = "https://github.com/buttplugio/buttplug.git"
readme = "../README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2021"
exclude = ["examples/**"]

[features]
# Basic features
default=["tokio-runtime", "client", "server", "serialize-json", "websockets", "btleplug-manager", "xinput-manager", "serial-manager", "lovense-dongle-manager", "lovense-connect-service-manager", "websocket-server-manager"]
client=[]
server=[]
serialize-json=[]
# Connectors
websockets=["serialize-json", "async-tungstenite", "native-tls"]
# Device Communication Managers
xinput-manager=["server"]
btleplug-manager=["server", "btleplug"]
serial-manager=["server", "serialport"]
lovense-dongle-manager=["server", "serialport", "hidapi"]
lovense-connect-service-manager=["server","reqwest"]
websocket-server-manager=["server", "websockets"]
# Runtime managers
tokio-runtime=["tokio/rt-multi-thread", "async-tungstenite/tokio-runtime", "async-tungstenite/tokio-native-tls"]
wasm-bindgen-runtime=["wasm-bindgen", "wasm-bindgen-futures"]
dummy-runtime=[]
# Compiler config
unstable=[]

[dependencies]
#buttplug_derive = "0.6.2"
buttplug_derive = { path = "../buttplug_derive" }
native-tls = { version = "0.2.10", optional = true }
futures = "0.3.23"
futures-util = "0.3.23"
async-trait = "0.1.57"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
serde_repr = "0.1.9"
uuid = { version = "1.1.2", features = ["serde"] }
url = "2.2.2"
btleplug = { version = "0.10.0", optional = true }
# btleplug = { path = "../../btleplug", optional = true}
# btleplug = { git = 'https://github.com/deviceplug/btleplug', branch = 'master', optional = true }
strum_macros = "0.24.3"
strum = "0.24.1"
once_cell = "1.13.1"
paste = "1.0.8"
lazy_static = "1.4.0"
byteorder = "1.4.3"
thiserror = "1.0.32"
async-tungstenite = { version = "0.17.2", optional = true }
wasm-bindgen-futures = { version = "0.4.32", optional = true }
cfg-if = "1.0.0"
tracing = "0.1.36"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.15", features = ["json"] }
dashmap = "5.3.4"
displaydoc = "0.2.3"
serialport = { version = "4.2.0", optional = true }
# Linux hidraw is needed here in order to work with the lovense dongle. libusb breaks it on linux.
# Other platforms are not affected by the feature changes.
hidapi = { version = "1.4.1", default-features = false, features = ["linux-static-hidraw", "illumos-static-libusb"], optional = true }
wasm-bindgen = { version = "0.2.82", optional = true }
tokio = { version = "1.20.1", features = ["sync", "macros", "io-util"] }
async-stream = "0.3.3"
prost = "0.11.0"
tokio-util = "0.7.3"
reqwest = { version = "0.11.11", optional = true, features = ["native-tls"] }
serde-aux = "3.1.0"
getset = "0.1.2"
os_info = "3.5.0"
jsonschema = { version = "0.16.0", default-features = false, features = ["resolve-file"] }
derivative = "2.2.0"
tokio-stream = "0.1.9"

[target.'cfg(windows)'.dependencies]
rusty-xinput = "1.2.0"

[dev-dependencies]
serde_yaml = "0.9.10"
test-case = "2.2.1"
tokio = { version = "1.20.1", features = ["io-std"] }
tracing-log = { version = "0.1.3", features = ["env_logger"] }

[lib]
name = "buttplug"
path = "src/lib.rs"
test = true
doctest = true
doc = true

# Only build docs on one platform (linux)
[package.metadata.docs.rs]
targets = []
# Features to pass to Cargo (default: [])
features = ["default", "unstable"]

[build-dependencies]
prost-build = "0.11.1"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.39.0", features = ["Devices_Bluetooth", "Foundation"] }
