[package]
name = "buttplug"
version = "0.3.1"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Buttplug Intimate Hardware Control Library"
license = "BSD-3-Clause"
homepage = "http://buttplug.io"
repository = "https://github.com/buttplugio/buttplug-rs.git"
readme = "../README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"
exclude = ["examples/**"]

[features]
default=["thread_pool_runtime", "client", "server", "serialize_json", "btleplug-manager", "client-ws-ssl", "xinput"]
client=[]
server=[]
serialize_json=[]
xinput=[]
thread_pool_runtime=[]
async_std_runtime=[]
tokio_runtime=[]
dummy_runtime=[]
btleplug-manager=["btleplug"]
client-ws=["client", "serialize_json", "async-tungstenite"]

[dependencies]
log = "0.4.8"
buttplug_derive = { path = "../buttplug_derive" }
# buttplug_derive = "0.2.0"
futures = { version = "0.3.5", features = ["thread-pool"] }
futures-util = "0.3.5"
async-trait = "0.1.33"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.53"
serde_repr = "0.1.5"
uuid = { version = "0.8.1", features = ["serde"] }
url = "2.1.1"
btleplug = { version = "0.4.3", optional = true }
# btleplug = { path = "../../btleplug", optional = true}
# btleplug = { git = 'https://github.com/deviceplug/btleplug', branch = 'master', optional = true }
strum_macros = "0.18.0"
strum = "0.18.0"
once_cell = "1.4.0"
paste = "0.1.16"
broadcaster = { version = "1.0.0", features = ["default-channels"] }
futures-channel = "0.3.5"
lazy_static = "1.4.0"
byteorder = "1.3.4"
valico = "3.4.0"
thiserror = "1.0.19"
async-tungstenite = { version = "0.5.0", features = ["async-std-runtime", "async-tls"], optional = true }
async-tls = "0.7.0"
rustls = { version = "0.17.0", features = ["dangerous_configuration"] }
webpki = "0.21.3"
evmap = "10.0.2"
evmap-derive = "0.1.0"
futures-timer = "3.0.2"
async-channel = "1.1.0"
 
[target.'cfg(windows)'.dependencies]
rusty-xinput = "1.2.0"

[dependencies.async-std]
version = "1.6.0"
default-features = false
features = ["std"]

[dev-dependencies]
env_logger = "0.7.1"

[lib]
name = "buttplug"
path = "src/lib.rs"
test = true
doctest = true
doc = true

# Only build docs on one platform (linux)
[package.metadata.docs.rs]
targets = []
