[package]
name = "buttplug"
version = "0.0.2"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Buttplug Intimate Hardware Control Library"
license = "BSD-3-Clause"
homepage = "http://buttplug.io"
repository = "https://github.com/buttplugio/buttplug-rs.git"
readme = "../README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"

[features]
default=["client-ws", "server"]
client=[]
server=[]
serialize_json=["serde", "serde_json", "serde_repr"]
client-ws=["client", "serialize_json", "ws", "url"]
client-ws-ssl=["client", "serialize_json", "ws", "url", "ws/ssl", "openssl"]

[dependencies]
log = "0.4.8"
buttplug_derive = { path = "../buttplug_derive" }
futures = "0.3.1"
futures-util = "0.3.1"
async-std = { version = "1.0.1", features = ["unstable"] }
async-trait = "0.1.17"
serde = { version = "1.0.102", features = ["derive"], optional = true }
serde_json = { version = "1.0.41", optional = true }
serde_repr = { version = "0.1.5", optional = true }
ws = { version = "0.9.1", features = ["ssl"], optional = true }
openssl = { version = "0.10.25", optional = true }
url = { version = "2.1.0", optional = true }

[dev-dependencies]
env_logger = "0.7.1"
futures-timer = "2.0.0"

[lib]
name = "buttplug"
path = "src/lib.rs"
test = true
doctest = true
doc = true
