[package]
name = "buttplug"
version = "0.0.2"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Buttplug Intimate Hardware Control Library"
license = "BSD-3-Clause"
homepage = "http://buttplug.io"
repository = "https://github.com/buttplugio/buttplug-rs.git"
readme = "README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"

[dependencies]
serde_json = "1.0.41"
serde = { version = "1.0.101", features = ["derive"]}
bytes = "0.4.12"
env_logger = "0.7.0"
log = "0.4.8"
quote = "1.0.2"
syn = "1.0.5"
buttplug_derive = { path = "../buttplug_derive" }
async-std = "0.99.9"
futures-channel-preview = "=0.3.0-alpha.19"
futures-preview = {version="0.3.0-alpha.19", features = ["async-await"]}
async-trait = "0.1.13"
serde_repr = "0.1.5"
ws = "0.9.0"
futures-util = "0.2.1"
pharos = "0.4.0"

[lib]
name = "buttplug"
path = "src/lib.rs"
test = true
doctest = true
doc = true
