[package]
name = "buttplug"
version = "0.0.2-beta.1"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Buttplug Intimate Hardware Control Library"
license = "BSD-3-Clause"
homepage = "http://buttplug.io"
repository = "https://github.com/buttplugio/buttplug-rs.git"
readme = "../README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"

[dependencies]
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
serde_repr = "0.1.5"
log = "0.4.8"
buttplug_derive = { path = "../buttplug_derive" }
futures-preview = {version="0.3.0-alpha.19", features = ["async-await"]}
futures-util-preview = "=0.3.0-alpha.19"
async-std = {version="0.99.11", features=["unstable"]}
async-trait = "0.1.17"

[dev-dependencies]
env_logger = "0.7.1"

[lib]
name = "buttplug"
path = "src/lib.rs"
test = true
doctest = true
doc = true
