[book]
authors = ["The buttplug-rs maintainers"]
language = "en"
multilingual = false
src = "src"
title = "The Rust Buttplug Book"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/buttplugio/buttplug-rs"
git-repository-icon = "fa-github"